---
- name: "Customizing Debian"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/configure-vim"
    - role: "roles/configure-tmux"
    - role: "roles/install-tools"
    - role: "roles/configure-system"
      users:
        - username: "{{ ansible_user_id }}" 
