---
- name: "install vim things"
  apt:
    name: vim
    state: present
    name: vim-gtk3
    state: present
  become: true
  become_method: sudo
- name: " Copy config files "
  copy:
    src: "{{ role_path }}/files/.vimrc"
    dest: "{{ ansible_env.HOME }}"
